/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demod2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(35652199a13efd770378e925f69d44b5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/demod2.h>
// pydoc.h is automatically generated in the build directory
#include <demod2_pydoc.h>

void bind_demod2(py::module& m)
{

    using demod2    = ::gr::ieee80211::demod2;


    py::class_<demod2, gr::block, gr::basic_block,
        std::shared_ptr<demod2>>(m, "demod2", D(demod2))

        .def(py::init(&demod2::make),
           py::arg("nrx"),
           py::arg("mupos"),
           py::arg("mugid"),
           D(demod2,make)
        )
        



        ;




}








