/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(equalizer2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(65d0ef2f6e089e22da0195bb9215bf6a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/equalizer2.h>
// pydoc.h is automatically generated in the build directory
#include <equalizer2_pydoc.h>

void bind_equalizer2(py::module& m)
{

    using equalizer2    = gr::ieee80211::equalizer2;


    py::class_<equalizer2, gr::block, gr::basic_block,
        std::shared_ptr<equalizer2>>(m, "equalizer2", D(equalizer2))

        .def(py::init(&equalizer2::make),
           D(equalizer2,make)
        )
        



        ;




}








