/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(modulation2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1f72642c853d665ee111c62bf543431)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/modulation2.h>
// pydoc.h is automatically generated in the build directory
#include <modulation2_pydoc.h>

void bind_modulation2(py::module& m)
{

    using modulation2    = gr::ieee80211::modulation2;


    py::class_<modulation2, gr::block, gr::basic_block,
        std::shared_ptr<modulation2>>(m, "modulation2", D(modulation2))

        .def(py::init(&modulation2::make),
           D(modulation2,make)
        )
        



        ;




}








