/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(modulation.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9bc1c05ab41acee029d00d2ea5e0da91)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/modulation.h>
// pydoc.h is automatically generated in the build directory
#include <modulation_pydoc.h>

void bind_modulation(py::module& m)
{

    using modulation    = gr::ieee80211::modulation;


    py::class_<modulation, gr::block, gr::basic_block,
        std::shared_ptr<modulation>>(m, "modulation", D(modulation))

        .def(py::init(&modulation::make),
           D(modulation,make)
        )
        



        ;




}








