/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pktgen.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8b0d89a929bd76db57f8b64d993c82ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/pktgen.h>
// pydoc.h is automatically generated in the build directory
#include <pktgen_pydoc.h>

void bind_pktgen(py::module& m)
{

    using pktgen    = ::gr::ieee80211::pktgen;


    py::class_<pktgen, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<pktgen>>(m, "pktgen", D(pktgen))

        .def(py::init(&pktgen::make),
           py::arg("lengthtagname") = "packet_len",
           D(pktgen,make)
        )
        



        ;




}








