/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preproc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(46396558f174830d2caf38509b774b0b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/preproc.h>
// pydoc.h is automatically generated in the build directory
#include <preproc_pydoc.h>

void bind_preproc(py::module& m)
{

    using preproc    = gr::ieee80211::preproc;


    py::class_<preproc, gr::block, gr::basic_block,
        std::shared_ptr<preproc>>(m, "preproc", D(preproc))

        .def(py::init(&preproc::make),
           D(preproc,make)
        )
        



        ;




}








