/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(signal2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ce4fd0c9e2dd89821d7ba4d5644dc934)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/signal2.h>
// pydoc.h is automatically generated in the build directory
#include <signal2_pydoc.h>

void bind_signal2(py::module& m)
{

    using signal2    = ::gr::ieee80211::signal2;


    py::class_<signal2, gr::block, gr::basic_block,
        std::shared_ptr<signal2>>(m, "signal2", D(signal2))

        .def(py::init(&signal2::make),
           D(signal2,make)
        )
        



        ;




}








